name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: step1
      - run: ls -la
      
