name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Grant execute permission for Gradle wrapper
      run: chmod +x ./gradlew

    - name: Build and test with Gradle
      run: ./gradlew build

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: app/build/reports/tests

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: app/build/outputs/apk/release/
