name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository # clone the repo to local ci workspace
        uses: actions/checkout@v2
#       - name: Set up our JDK environment # setup JDK environment: mandatory as we need to build  android project
#         uses: actions/setup-java@v1.4.3
      - name: install dependencies
        run: yarn install
      - name: build android
        working-directory: ./android
#         run: ./gradlew build
        run: ls -la
      - name: ls
        working-directory: ./
        run: cd ./android/app/build/outputs/apk/debug && ls -la
